# pandas 정리

## import pandas as pd

### * From list of lists, array of arrays, list of series

2차원 리스트나 2차원 numpy array로 DataFrame을 만들 수 있습니다. 심지어 pandas Series를 담고 있는 리스트로도 DataFrame을 만들 수 있습니다.  

따로 column과 row(index)에 대한 설정이 없으면 그냥 0, 1, 2, ... 순서로 값이 매겨집니다.


import numpy as np

import pandas as pd

two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]

two_dimensional_array = np.array(two_dimensional_list)

list_of_series = [

    pd.Series(['dongwook', 50, 86]), 
    
    pd.Series(['sineui', 89, 31]), 
    
    pd.Series(['ikjoong', 68, 91]), 
    
    pd.Series(['yoonsoo', 88, 75])
]

아래 셋은 모두 동일합니다

df1 = pd.DataFrame(two_dimensional_list)

df2 = pd.DataFrame(two_dimensional_array)

df3 = pd.DataFrame(list_of_series)

print(df1)

-->       

          0   1   2
          
0  dongwook  50  86

1    sineui  89  31

2   ikjoong  68  91

3   yoonsoo  88  75

### * From dict of lists, dict of arrays, dict of series

파이썬 사전(dictionary)으로도 DataFrame을 만들 수 있습니다.

사전의 key로는 column 이름을 쓰고, 그 column에 해당하는 리스트, numpy array, 혹은 pandas Series를 사전의 value로 넣어주면 됩니다.

import numpy as np

import pandas as pd

names = ['dongwook', 'sineui', 'ikjoong', 'yoonsoo']

english_scores = [50, 89, 68, 88]

math_scores = [86, 31, 91, 75]

dict1 = {

    'name': names, 
    
    'english_score': english_scores, 
    
    'math_score': math_scores
    
}

dict2 = {

    'name': np.array(names), 
    
    'english_score': np.array(english_scores), 
    
    'math_score': np.array(math_scores)
    
}

dict3 = {

    'name': pd.Series(names), 
    
    'english_score': pd.Series(english_scores), 
    
    'math_score': pd.Series(math_scores)
    
}


아래 셋은 모두 동일합니다

df1 = pd.DataFrame(dict1)

df2 = pd.DataFrame(dict2)

df3 = pd.DataFrame(dict3)


print(df1)

-->

       name  english_score  math_score
       
0  dongwook             50          86

1    sineui             89          31

2   ikjoong             68          91

3   yoonsoo             88          75

### * From list of dicts

리스트가 담긴 사전이 아니라, 사전이 담긴 리스트로도 DataFrame을 만들 수 있습니다.

import numpy as np

import pandas as pd

my_list = [

    {'name': 'dongwook', 'english_score': 50, 'math_score': 86},
    
    {'name': 'sineui', 'english_score': 89, 'math_score': 31},
    
    {'name': 'ikjoong', 'english_score': 68, 'math_score': 91},
    
    {'name': 'yoonsoo', 'english_score': 88, 'math_score': 75}
    
]

df = pd.DataFrame(my_list)

print(df)

-->

   english_score  math_score      name
   
0             50          86  dongwook

1             89          31    sineui

2             68          91   ikjoong

3             88          75   yoonsoo

### * pandas DataFrame에 데이터 담는 예시

import pandas as pd

two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]

my_df = pd.DataFrame(two_dimensional_list, columns=['name', 'english_score', 'math_score'], index=['a', 'b', 'c', 'd'])

my_df

-->

    name english_score math_score

a dongwook 50 86

b sineui 89 31

c ikjoong 68 91

d yoonsoo 88 75


// dataframe에서 row를 index라고도 부름.

### * pandas로 데이터 읽어들이기

import pandas as pd

A = pd.read_csv('경로')

A

여기서 

A = pd.read_csv('경로', index_col = 0)

index_col = 0 를 추가하면 0번 column을 index 이름으로 설정됨.

### * DataFrame 인덱싱

1번 로우, 1번 컬럼 출력하기 A.loc['row1', 'column1']

1번 로우 다 출력하기  A.loc['row1', :] or A.loc['row1']

1번 컬럼 다 출력하기 A.loc[:, 'column1'] or A['column1']  <-- 확인

### * DataFrame 슬라이싱

1번 ~ 3번 로우 출력하기 A.loc['row1' : 'row3']

1번 ~ 3번 컬럼 출력하기 A.loc[: , 'column1' : 'column3']

1번 ~ 3번 로우, 컬럼 출력하기 A.loc['row1' : 'row3' , 'column1' : 'column3']

컬럼을 슬라이싱 할 때 .loc 생략 못함

### * DataFrame 위치로 인덱싱

2번 로우, 4번 컬럼의 값 출력하기 A.iloc[2,4]

1번 로우와 3번 로우, 1번 컬럼과 4번 컬럼의 값 출력하기 A.iloc[[1,3],[1,4]]

슬라이싱도 가능

### * DataFrame 에 값 쓰기

위에서 본 인덱싱 슬라이싱에 = '값'만 뒤에 추가해주면 됨.

컬럼 간편 출력 가능 A['row1'] = '1'

ex) A.loc['row1', column1'] = '2'

### * DataFrame 에 값 추가/삭제

#### 데이터 추가

데이터 프레임에 없는 값을 쓰면 됨

로우 추가 A.loc['new'] = ['ha','haha']

컬럼 추가 A['이름'] = '민경호'

#### 데이터 삭제

삭제하고 싶은 값과 로우인지 컬럼인지와 기존 데이터에 영향 끼치는지 넘기기

A.drop('new', axis='index', inplace=False)

inplace를 True로 할 시 기존 데이터에 영향

A.drop('이름', axis='columns', inplace=True)

### * index/column 설정하기

A.rename(columns={'old' : 'new'})

이거도 마찬가지로 기존 데이터에 영향 끼치려면

A.rename(columns={'old' : 'new'}, inplace=True)


인덱스의 이름 붙히기
A.index.name = 'Name'

인덱스 자체를 바꾸기
A.set_index('column3') 3번 컬럼으로 바뀜

### * 큰 DataFrame 살펴보기

윗 줄만 보기
A.head(3)

아랫줄만 보기
A.tail(3)

데이터 크기 보기
A.shape
-> (5, 3) 로우5개 컬럼3개

컬럼에 대한 기본 정보 보기
A.info()

통계정보 보기 
A.describe()

특정 값으로 정렬
A.sort_values(by='column1')

내림차순으로 정렬
A.sort_values(by='column1', ascending=False)

마찬가지로 기존 데이터 영항 끼치려면 A.sort_values(by='column1', ascending=False, inplace=True)

### * 큰 Series 살펴보기

겹치는 애들 제외하고 무엇이 있는지 A['column1'].unique() 

각각 몇개씩 있는지 A['column1'].value_counts()

요약본 A['column1'].describe()